# Generated by Django 3.1.7 on 2021-05-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbbs1', '0002_question_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='modify_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
